# Generated by Django 6.0 on 2025-12-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Заблокированный токен', 'verbose_name_plural': 'Заблокированные токены'},
        ),
    ]
