# Generated by Django 6.0 on 2025-12-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesselement',
            options={'verbose_name': 'Бизнес-элемент', 'verbose_name_plural': 'Бизнес-элементы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
    ]
